### ISSUE TITLE
User configurable parameters unclear

### ISSUE THREAD

**Issue by philippnagel** [Th3Jock3R/LinuxGSM-Arma3-Mod-Update#3]
Hi,

I am using an A3 server set up using LinuxGSM.

It is not obvious to me which values I have to enter for "A3_SERVER_FOLDER" and "A3_SERVER_DIR".

My current config looks like this:

A3_SERVER_FOLDER = "lgsm"
A3_SERVER_DIR = "/home/arma3".format(A3_SERVER_FOLDER)

This throws the following type error: TypeError: 'NoneType' object is not iterable.

I am probably doing something wrong. Are you able to point me towards a solution?

**Comment by Th3Jock3R** [comment]
Hi,

the armaserver file is in which directory?

If it is in the /home/arma3 directory, set the vars:

````
A3_SERVER_FOLDER = ""
A3_SERVER_DIR = "/home/arma3"
````

If the file is in /home/arma3/lgsm
````
A3_SERVER_FOLDER = ""
A3_SERVER_DIR = "/home/arma3/lgsm"
````
or
````
A3_SERVER_FOLDER = "lgsm"
A3_SERVER_DIR = "/home/arma3/{}".format(A3_SERVER_FOLDER)
````

**Comment by Revy106106** [comment]
I am having the exact same issues

my server is setup with gsm aswell 
(this holds the steamcmd and arma3server file)
/home/arma3server/

but the actual game is in 

/home/arma3server/serverfiles 
which also holds another arma3server file

non stop getting Select Modlist Files Found
Traceback (most recent call last):
  File "./a3update.py", line 34, in <module>
    for file in f.sort():
TypeError: 'NoneType' object is not iterable

i also have a modlist in the modlist folder all permissions set correctly but still no luck hmm

**Comment by Th3Jock3R** [comment]
Hi,

just comited a small fix for the sorting of the modlist array. Please try again with newest version.
